config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'

  put '/unsafe_messages/:id/create', to: 'unsafe_messages#create', as: 'mark_as_unsafe'

  put '/safe_messages/:id/create', to: 'safe_messages#create', as: 'mark_as_safe'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :author, presence: true
  validates :author_slug, presence: true
  validates :content, presence: true

  scope :safe, -> { where(kind: 'safe') }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @safe_mode = to_boolean(params[:safe] || true)
    @toggle_safe_mode = !@safe_mode
    if @safe_mode == false
      @messages = Message.all
    else
      @messages = Message.safe
    end
  end

end

app/controllers/safe_messages_controller.rb
class SafeMessagesController < ApplicationController

  def create
    message = Message.find(params[:id])
    message.update(kind: 'safe')
    redirect_to params[:redirect_to]
  end

end

app/controllers/unsafe_messages_controller.rb
class UnsafeMessagesController < ApplicationController

  def create
    message = Message.find(params[:id])
    message.update(kind: 'unsafe')
    redirect_to params[:redirect_to]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def to_boolean(value)
    if value.to_s == 'true'
      true
    elsif value.to_s == 'false'
      false
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SafeTwitts</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Image and text -->
    <nav class="navbar navbar-light bg-faded">
      <div class="navbar-brand" href="#">
        <%= image_tag "twitter_logo.png", width: 30, class: "d-inline-block align-top" %>
        Safe Twitts
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/messages/_toggle.html.haml
.container-fluid
  #toggle
    .row
      .col-sm-6.text-right
        Safe Mode
      .col-sm-6
        = link_to root_path(safe: toggle_safe_mode), id: 'toggle_safe_mode' do
          %label.switch
            %input{type: 'checkbox', checked: safe_mode}
            .slider.round

app/views/messages/index.html.haml
= render partial: 'toggle', locals: {toggle_safe_mode: @toggle_safe_mode, safe_mode: @safe_mode }

#messages.grid
  - @messages.each do |msg|
    .row.message{id: dom_id(msg)}
      .col-sm-2= msg.author
      .col-sm-10
        %span= msg.content
        - if msg.kind == 'safe'
          = link_to mark_as_unsafe_path(msg.id, redirect_to: root_url(safe: @safe_mode)), class: 'is_unsafe', method: :put do
            %button.btn.btn-default.unsafe= "Mark as unsafe"
        - else
          = link_to mark_as_safe_path(msg.id, redirect_to: root_url(safe: @safe_mode)), class: 'is_safe', method: :put do
            %button.btn.btn-default.safe= "Mark as safe"